# Deployment template for techtrends
apiVersion: apps/v1
kind: Deployment

metadata:
  labels:
    app: {{ .Values.appname }}
    tag: {{ .Values.tag }}
  name: {{ .Values.appname }}
  namespace: {{ .Values.namespace.name }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appname }}
      tag: latest

  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
        tag: latest
        
    spec:
      containers:
        # Path to the image
      - image: {{ .Values.image.dockerRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Values.appname }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.path }}
            port: {{ .Values.readinessProbe.port }}
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.path }}
            port: {{ .Values.livenessProbe.port }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
